export const ACTION_LOG_IN = 'ACTION_SIGN_IN';
export const ACTION_LOG_UP = 'ACTION_SIGN_UP';
export const ACTION_LOG_OUT = 'ACTION_SIGN_OUT';
export const ACTION_ERROR = 'ACTION_ERROR';
export const ACTION_LOAD_CURRENT_USER = 'ACTION_LOAD_CURRENT_USER';
export const ACTION_UPDATE_CURRENT_USER = 'ACTION_LOAD_CURRENT_USER';